[package]
name = "advent_of_code_2020"
version = "0.1.0"
authors = ["giulio <giuliop@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "util"
path = "src/lib.rs"

[dependencies]
